version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    expose:
      - 3306
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: commerce_core
      MYSQL_DATABASE: commerce_core
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - commerce_core



  phpmyadmin:
    container_name: phpMyAdminNr2
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '127.0.0.1:8000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - commerce_core

networks:
  commerce_core:

volumes:
  db_data: